---

- name: Install shells
  become: true
  package:
    name:
      - zsh
      - dash
    state: present

- name: Set default shell to dash
  become: true
  file:
    path: /bin/sh
    src: /bin/dash
    state: link

- name: Set user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Download dotfiles
  git:
    clone: true
    bare: true
    repo: git@github.com:RoryNesbitt/dotfiles
    dest: $HOME/.config/dotfiles
    update: false

- name: Checkout dotfiles
  shell: |
    git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME checkout
    git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME pull
