---

- name: Install shells
  become: true
  package:
    name:
      - zsh
      - dash
    state: present
  tags:
    - shell
    - zsh
    - dash

- name: Set default shell to dash
  become: true
  file:
    path: /bin/sh
    src: /bin/dash
    state: link
  tags:
    - shell
    - dash
