---

- hosts: all
  gather_facts: true
  pre_tasks:
    - name: Use un_get on Unraid
      tags: always
      ansible.builtin.set_fact:
        ansible_package_use: un_get
      when: "'unraid' in group_names"
    - import_tasks: tasks/upgrade.yml

  roles:
    - ssh
    - shell
    - git
    - dotfiles

- hosts: home
  gather_facts: false
  roles:
    - zsh

- hosts: nvim
  gather_facts: false
  roles:
    - nvim

- hosts: pvim
  gather_facts: false
  roles:
    - pvim
