---

- hosts: all
  pre_tasks: []
  roles:
    # - base
    - ssh
    - shell

- hosts: home
  gather_facts: false
  roles:
    - zsh

- hosts: all
  gather_facts: false
  roles:
    - git
    - dotfiles

- hosts: nvim
  gather_facts: false
  roles:
    - nvim

- hosts: pvim
  gather_facts: false
  roles:
    - pvim
