---

- hosts: all
  pre_tasks:
    - import_tasks: tasks/upgrade.yml

  roles:
    - ssh
    - shell
    - git
    - dotfiles

- hosts: home
  gather_facts: false
  roles:
    - zsh

- hosts: nvim
  gather_facts: false
  roles:
    - nvim

- hosts: pvim
  gather_facts: false
  roles:
    - pvim
