---

- name: Installing desktop programs
  become: true
  package:
    name:
      - ghostty
      - thunar
      - waterfox
      - hyprlauncher
      - hyprshot
      - waybar
      - rofi
      - ttf-cascadia-code-nerd
    state: present
  tags:
    - desktop
