- name: Install all the things
  hosts: localhost
  tasks:
    - name: Installing desktop programs
      package:
        name:
          - kitty
          - firefox
          - vivaldi
          - steam
          - tmux
          - wine
          - yarn
          - python-pip
          - xclip
          - fzf
          - ripgrep
          - cmake
          - ansible
          - flameshot
        state: present
      become: true
    - name: Installing AUR packages
      command: >
        yay -Syu --noconfirm
        realvnc-vnc-viewer
        openconnect
        teams
        nerd-fonts-fira-code
      when: ansible_distribution == "Archlinux"
