- name: Setup Neovim
  hosts: localhost
  tasks:

    - name: Install Neovim
      package:
        name:
          - neovim
          - python-pynvim
        state: present
      become: true

    - name: Cloning RNvim
      git:
        clone: true
        repo: git@github.com:RoryNesbitt/RNvim
        dest: $HOME/.config/nvim
