- name: Setup Neovim
  hosts: localhost
  become: true
  tasks:
    - name: Install Neovim
      package:
        name:
          - neovim
          - python-pynvim
        state: present

- name: Download RNvim
  hosts: localhost
  tasks:
    - name: Cloning RNvim
      git:
        clone: true
        repo: git@github.com:RoryNesbitt/RNvim
        dest: $HOME/.config/nvim
