- name: Install shells
  hosts: localhost
  become: true
  tasks:
    - name: Install shells
      package:
        name:
          - zsh
          - dash
        state: present

- name: Use dash
  hosts: localhost
  become: true
  tasks:
    - name: Set default shell to dash
      shell: |
        rm -f /bin/sh
        ln -s /bin/dash /bin/sh

- name: Use zsh
  hosts: localhost
  become: true
  tasks:
    - name: Set user shell to dash
      user:
        name: rory
        shell: /bin/zsh

- name: Download dotfiles
  hosts: localhost
  tasks:
    - name: Download dotfiles
      git:
        clone: true
        bare: true
        repo: git@github.com:RoryNesbitt/dotfiles
        dest: $HOME/.config/dotfiles
