- name: Install ZSH
  hosts: localhost
  become: true
  tasks:
    - name: Install ZSH
      package:
        name: zsh
        state: present

- name: Download dotfiles
  hosts: localhost
  tasks:
    - name: Download dotfiles
      git:
        clone: true
        bare: true
        repo: git@github.com:RoryNesbitt/dotfiles
        dest: $HOME/.config/dotfiles
