---

- name: Download dotfiles
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/dotfiles
    dest: $HOME/.config/dotfiles
    update: false
  tags:
    - dotfiles

- name: Checkout dotfiles
  shell: $HOME/.config/dotfiles/dots link $HOME/.config/dotfiles
  tags:
    - dotfiles
