---

- name: Check ssh directory exists
  file:
    dest: $HOME/.ssh
    state: directory
  tags:
    - ssh

- name: Add ssh key
  copy:
    src: "{{ ssh_key }}"
    dest: $HOME/.ssh/id_ed25519
    mode: 0600
  tags:
    - ssh

- name: Add public key
  copy:
    src: "{{ ssh_key }}.pub"
    dest: $HOME/.ssh/id_ed25519.pub
    mode: 0644
  tags:
    - ssh
