---

- name: Check ssh directory exists
  file:
    dest: $HOME/.ssh
    state: directory

- name: Add ssh key
  copy:
    src: "ssh_keys/{{ ssh_key }}"
    dest: $HOME/.ssh/
    mode: 0600

- name: Add public key
  copy:
    src: "ssh_keys/{{ ssh_key }}.pub"
    dest: $HOME/.ssh/
    mode: 0644

- name: Use new ssh key
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', 'ssh_keys/{{ ssh_key }}.pub') }}"
