---

- name: Checking for dependencies
  become: true
  package:
    name:
      - fuse3
      - build-essential
    state: present
  tags:
    - neovim
    - pvim
  when:
    - ansible_facts.os_family == 'Debian'

- name: Cloning pvim
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/pvim
    dest: "{{ ansible_facts.env.HOME }}/.local/pvim"
    force: true
    update: true
  tags:
    - neovim
    - pvim

- name: Cloning RNvim
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/RNvim
    dest: "{{ ansible_facts.env.HOME }}/.local/pvim/config"
    update: true
  tags:
    - neovim
    - pvim
    - rnvim

