---

- name: Checking for dependencies
  become: true
  package:
    name:
      - fuse
      - build-essential
    state: present
  tags:
    - neovim
    - pvim
  when:
    - ansible_distribution|string == 'Ubuntu'

- name: Cloning pvim
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/pvim
    dest: $HOME/.local/pvim
    force: true
  tags:
    - neovim
    - pvim

- name: Cloning RNvim
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/RNvim
    dest: $HOME/.local/pvim/config
  tags:
    - neovim
    - pvim
    - rnvim

