---

- name: Install Neovim
  become: true
  package:
    name:
      - neovim
    state: present
  tags:
    - neovim
    - nvim

- name: Cloning RNvim
  git:
    clone: true
    repo: git@github.com:RoryNesbitt/RNvim
    dest: "{{ ansible_facts.env.HOME }}/.config/nvim"
    update: true
  tags:
    - neovim
    - nvim
    - rnvim
